export const rooms = [
    {
        id: "1",
        roomNumber: "101",
        type: "Single",
        pricePerNight: 100.0,
        capacity: 1,
        isAvailable: true,
        location: "Yangon",
        title: "Cozy Single Room",
        description: `This cozy single room is designed for solo travelers seeking comfort and relaxation. The room features a plush queen-sized bed with premium linens, a spacious work desk, and a comfortable armchair. Large windows allow natural light to flood the room, offering a bright and airy atmosphere. Modern amenities include high-speed Wi-Fi, a flat-screen TV, and a mini-fridge. The en-suite bathroom is equipped with a rain shower, complimentary toiletries, and soft towels. Perfect for business travelers or those exploring the city, this room provides a peaceful retreat after a busy day.`,
        images: [
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room1-1" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room1-2" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room1-3" },
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room1-4" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room1-5" },
        ],
    },
    {
        id: "2",
        roomNumber: "102",
        type: "Double",
        pricePerNight: 150.0,
        capacity: 2,
        isAvailable: true,
        location: "Mandalay",
        title: "Spacious Double Room",
        description: `Ideal for couples or small families, this spacious double room offers a comfortable king-sized bed and a cozy sitting area. The room is decorated in warm, neutral tones, creating a welcoming and relaxing environment. Large windows provide stunning views of the city skyline, and blackout curtains ensure a restful night's sleep. Amenities include a flat-screen TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom features a bathtub, a separate rain shower, and luxurious toiletries. Whether you're here for business or leisure, this room provides the perfect blend of comfort and convenience.`,
        images: [
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room2-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room2-2" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room2-3" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room2-4" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room2-5" },
        ],
    },
    {
        id: "3",
        roomNumber: "103",
        type: "Suite",
        pricePerNight: 250.0,
        capacity: 4,
        isAvailable: false,
        location: "Bagan",
        title: "Luxury Suite",
        description: `Experience the ultimate in luxury with this spacious suite, perfect for families or groups. The suite features a separate living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom boasts a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows offer breathtaking views of the surrounding landscape. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. This suite is designed to provide a truly indulgent stay, combining elegance with modern comforts.`,
        images: [
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room3-1" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room3-2" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room3-3" },
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room3-4" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room3-5" },
        ],
    },
    {
        id: "4",
        roomNumber: "104",
        type: "Single",
        pricePerNight: 120.0,
        capacity: 1,
        isAvailable: true,
        location: "Shan",
        title: "Elegant Single Room",
        description: `This elegant single room is designed for the discerning traveler who appreciates style and comfort. The room features a comfortable queen-sized bed with high-quality linens, a sleek work desk, and a cozy reading nook. The modern decor is complemented by soft lighting and tasteful artwork. Amenities include a smart TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom is equipped with a rain shower, premium toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a serene and sophisticated retreat.`,
        images: [
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room4-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room4-2" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room4-3" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room4-4" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room4-5" },
        ],
    },
    {
        id: "5",
        roomNumber: "105",
        type: "Double",
        pricePerNight: 180.0,
        capacity: 2,
        isAvailable: true,
        location: "Yangon",
        title: "Deluxe Double Room",
        description: `This deluxe double room offers a perfect blend of comfort and style, ideal for couples or friends traveling together. The room features a king-sized bed with luxurious bedding, a cozy seating area, and a private balcony with stunning city views. The modern decor is complemented by soft lighting and elegant furnishings. Amenities include a flat-screen TV, a coffee maker, and a minibar. The en-suite bathroom features a rain shower, premium toiletries, and plush towels. Whether you're here for business or leisure, this room provides a relaxing and enjoyable stay.`,
        images: [
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room5-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room5-2" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room5-3" },
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room5-4" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room5-5" },
        ],
    },
    {
        id: "6",
        roomNumber: "106",
        type: "Suite",
        pricePerNight: 300.0,
        capacity: 4,
        isAvailable: false,
        location: "Mandalay",
        title: "Premium Suite",
        description: `Indulge in the ultimate luxury with this premium suite, designed for those who seek the finest accommodations. The suite features a spacious living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom offers a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows provide breathtaking views of the city skyline. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. This suite is perfect for families or groups looking for a luxurious and memorable stay.`,
        images: [
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room6-1" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room6-2" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room6-3" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room6-4" },
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room6-5" },
        ],
    },
    {
        id: "7",
        roomNumber: "107",
        type: "Single",
        pricePerNight: 110.0,
        capacity: 1,
        isAvailable: true,
        location: "Bagan",
        title: "Comfortable Single Room",
        description: `This comfortable single room is perfect for solo travelers seeking a relaxing and hassle-free stay. The room features a cozy queen-sized bed with soft linens, a compact work desk, and a comfortable armchair. The minimalist decor creates a calming atmosphere, while large windows let in plenty of natural light. Amenities include a flat-screen TV, high-speed Wi-Fi, and a mini-fridge. The en-suite bathroom is equipped with a rain shower, complimentary toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a peaceful and comfortable retreat.`,
        images: [
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room7-1" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room7-2" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room7-3" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room7-4" },
            { url: "https://images.pexels.com/photos/6782346/pexels-photo-6782346.jpeg", public_id: "room7-5" },
        ],
    },
    {
        id: "8",
        roomNumber: "108",
        type: "Double",
        pricePerNight: 160.0,
        capacity: 2,
        isAvailable: true,
        location: "Shan",
        title: "Romantic Double Room",
        description: `This romantic double room is perfect for couples looking for a cozy and intimate getaway. The room features a king-sized bed with luxurious bedding, a comfortable seating area, and soft lighting to create a warm and inviting atmosphere. Large windows offer stunning views of the surrounding landscape, and blackout curtains ensure a restful night's sleep. Amenities include a flat-screen TV, a coffee maker, and a minibar. The en-suite bathroom features a bathtub, a separate rain shower, and premium toiletries. Whether you're celebrating a special occasion or simply enjoying a quiet retreat, this room provides the perfect setting.`,
        images: [
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room8-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room8-2" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room8-3" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room8-4" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room8-5" },
        ],
    },
    {
        id: "9",
        roomNumber: "109",
        type: "Suite",
        pricePerNight: 280.0,
        capacity: 4,
        isAvailable: false,
        location: "Yangon",
        title: "Executive Suite",
        description: `This executive suite is designed for travelers who demand the best in comfort and convenience. The suite features a separate living area with a plush sofa, a dining table, and a fully equipped kitchenette. The bedroom offers a king-sized bed with premium bedding, and the en-suite bathroom includes a Jacuzzi tub and a separate rain shower. Floor-to-ceiling windows provide stunning views of the city skyline. Additional amenities include a 55-inch flat-screen TV, a Nespresso machine, and a private balcony. Whether you're here for business or leisure, this suite offers a luxurious and memorable stay.`,
        images: [
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room9-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room9-2" },
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room9-3" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room9-4" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room9-5" },
        ],
    },
    {
        id: "10",
        roomNumber: "110",
        type: "Single",
        pricePerNight: 130.0,
        capacity: 1,
        isAvailable: true,
        location: "Mandalay",
        title: "Modern Single Room",
        description: `This modern single room is perfect for solo travelers who appreciate contemporary design and comfort. The room features a comfortable queen-sized bed with high-quality linens, a sleek work desk, and a cozy reading nook. The minimalist decor is complemented by soft lighting and tasteful artwork. Amenities include a smart TV, a coffee maker, and a well-stocked minibar. The en-suite bathroom is equipped with a rain shower, premium toiletries, and fluffy towels. Whether you're here for work or leisure, this room offers a serene and sophisticated retreat.`,
        images: [
            { url: "https://images.pexels.com/photos/7512038/pexels-photo-7512038.jpeg", public_id: "room10-1" },
            { url: "https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg", public_id: "room10-2" },
            { url: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg", public_id: "room10-3" },
            { url: "https://images.pexels.com/photos/7060811/pexels-photo-7060811.jpeg", public_id: "room10-4" },
            { url: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg", public_id: "room10-5" },
        ],
    },
];